source 'https://rubygems.org'
ruby '2.3.4'

gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.1.3'
gem 'redis', '~> 3.0'
gem 'cloudinary', '1.1.7'
gem 'attachinary', github: 'assembler/attachinary'
gem 'jquery-fileupload-rails'
gem 'coffee-rails'
gem 'carrierwave', '~> 0.11.2'
gem 'omniauth-facebook'
gem 'koala', '~> 2.4'

gem 'sidekiq'
gem 'sidekiq-failures', '~> 1.0'
gem 'sidekiq-scheduler'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem "jquery-slick-rails"
gem 'twilio-ruby', '~> 5.2.0'
gem 'fullpage-rails'

group :development, :test do
  gem 'pry-byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
